### ISSUE TITLE
[Feature] Rework the GUI

### ISSUE THREAD

**Issue by Peyphour** [jabbink/PokemonGoBot#1001]
Now that I added a lot of functionnalities through the REST API, I would like to rework the GUI to integrate those changes : 
 * Evolve/Powerup/Transfer/Rename/favorite pokemons through the GUI
 * See, drop items, use incense/lucky egg
 * Show profile/pokedex
 * Protect the GUI via password

What do you think ?

**Comment by swtrpeter** [comment]
Sounds great

**Comment by NoobWithBoobs** [comment]
Great idea, could I help with re-organizing the ui?

**Comment by Turtizzle** [comment]
#789 :)

**Comment by Peyphour** [comment]
@Turtizzle, just saw this one before posting, It's the same idea except that I have more features ^^

**Comment by NoobWithBoobs** [comment]
Protect the GUI via password would be helpful, especially if it's different password for each bot.

**Comment by Peyphour** [comment]
@NoobWithBoobs Don't know yet how I will implement that, but the REST API is already secured via password so maybe I will use the same. For helping me, I already forked the original repo of the GUI. I have still a feature I need to work on but as soon as I finish, I will get working on this one

**Comment by NoobWithBoobs** [comment]
Awesome, tag me whenever you want help. I'd love to help 👍

**Comment by Turtizzle** [comment]
Yea, I know that, I just thought I'd mention it here, since its related.

About the more features:
I'd say evolve and transfer are most important right now, optionally powerup.
Rename and favorite are hardly useful for botting, and especially renaming requires an additional input form.
I personally have no use for dedicated item management, but I see that ppl might want it.
Profile and Pokedex would be my last priority, though.
As for delivering certain features in time, I'd focus on what helps most. :P

**Comment by NoobWithBoobs** [comment]
Power up would be great because the in-app animation is slow and annoying.

**Comment by Peyphour** [comment]
Well, all actions on pokemon can be done by adding a clickable icon on the pokemon image which start the desired action. We'll see for the rest when I start

**Comment by NoobWithBoobs** [comment]
if you do consider mass transfer, this workflow would be awesome. 

0. Transfer = Clean up and keep rarely high iv cp.
1. Power Up = Max out CP
2. Evolve
3. Favorites (but also have Never Transferable, high IV or Rare pokemon mew, mewtwo)

**Comment by Peyphour** [comment]
I don't think I'll do that, I want this to be the more simple as possible. I the user want an action he will have to click on the button

**Comment by NoobWithBoobs** [comment]
Considering we already have an outline of which pokemon to keep and drop in the config file, wouldn't mass transfer be just a button?

**Comment by Peyphour** [comment]
I saw someone talking about refactoring the logic behind which pokemon to keep/drop (don't remember who) so I would prefer not doing anything to this side

**Comment by Turtizzle** [comment]
I'd prefer having a list of pokemon that is sortable by different columns.
In this list, one could select multiple pokemon at the same time (including holding CTLR or SHIFT to expand your current selection, just like in any other list).
Then click "transfer" once to transfer all selected pokemon.
This would be much more convenient than having to click on a small transfer-icon for every single pokemon.

Imagine having 100 Pidgeotto and you'd like to get rid of 78 of them.
Sort by pokemon-#NR, then by CP, select the strongest one you'd like to transfer, scroll all the way down, hold SHIFT and select the last one, transfer, done.

**Comment by Mixone-FinallyHere** [comment]
This is all amazing and beautiful but a **TON** of work.
And given how API has some time sensitive send/recv somewhere I don't know if adding threads in the code to support this will slow it down to the point of being an issue.

**Comment by Peyphour** [comment]
This isn't as much work as you may think. 

> And given how API has some time sensitive send/recv somewhere I don't know if adding threads in the code to support this will slow it down to the point of being an issue.

What are you talking about ? I didn't understand you on this

@Turtizzle : This idea is much more practical

**Comment by NoobWithBoobs** [comment]
@Turtizzle does sound a lot better!

**Comment by Mixone-FinallyHere** [comment]
Well the "gui" works on a socket server through your browser at certain port, there is a certain amount of data that goes in and out each of which is transmitted through different buffers and (I think) each socket on a different thread.
That in itself has tiny, yet existant mili or even micro seconds of delay.
Then the thread has to join the main bot one, which is sending and receiving data continuously, and there you have a sudden big data dump to parse (get correct ids of pokemon and prepare a request for each) since the game itself handles transfers one by one (you cant transfer three pokemon at the same time).
Now you have lets say 10 transfers ready the game will receive them  and either:
- Notice you are a bot (human players wont be able to do 10 transfers in a second)
- Have an issue if a thread join paused a loop too long and caused a delay in its communication with server

To be exact I beleive it is unknown22 that has the time delay issues

**Comment by Peyphour** [comment]
The REST API has no common point with the socket server and runs in different threads. The communication with the REST API will most likely be done via AJAX calls.

Regarding the handling of multiple transfer/evolve/powerup/rename/favorite, the simpliest solution would be to insert a delay (500ms for example) between each request sent to the PoGO API

**Comment by Turtizzle** [comment]
I don't think the GUI should bother with delaying transfers.
Send the entire list you'd like to get rid of, switch the GUI into a "applying changes" state that does not allow new input, receive the list on the BOT-side and add it to your "to-be-transferred" list.
Work on that list (with whatever delay) until its empty. Re-enable GUI interaction.

**Comment by Mixone-FinallyHere** [comment]
Yes of course my doubt is if that new group of calls will cause a significant time delay or not, because the time sensitive functions are probably quite nitpicky

**Comment by Mixone-FinallyHere** [comment]
@Turtizzle hadn't thought of that, good idea!

**Comment by NoobWithBoobs** [comment]
@Mixone-FinallyHere time delay could be a tweakable an option.

**Comment by Peyphour** [comment]
@Turtizzle  Maybe implementing a Queue would be more practical here, no need to swich the GUI state

**Comment by Turtizzle** [comment]
@Peyphour If pokemon are not removed at the same time you click "transfer", you'd be able to fire new commands with them, e.g. powering them up or transferring them a second time, leading to random errors. I'd lock it to prevent weird results.

**Comment by Peyphour** [comment]
Or perhaps remove them immediatly from the GUI ?

**Comment by Turtizzle** [comment]
Well that might work for transferring them, given nothing else goes wrong (hard to tell since its all parallelized).
Evolving is a different issue.. It'll be a lot harder to predict how the pokemon changes immediately.
I think the best would be locking it in any case, until operations are done.
Thats what we have multi selection for in the first place, anyway.
If there is more stuff to transfer, you'd have selected that already in the first place.

**Comment by Mixone-FinallyHere** [comment]
There actually is a stat sheet for evolution (dunno where) for example Magikarp gets x10.5 CP at evolve but the rest are all between 1.3 and 2.3 or something like that

**Comment by NoobWithBoobs** [comment]
http://imgur.com/gallery/CWMyC

**Comment by Mixone-FinallyHere** [comment]
I saw a page that had an actual calculator for it
That would be a nice add-on as well

**Comment by Turtizzle** [comment]
I don't think there is a static multiplicator, it depends on some stuff.
Magikarp can be between 10.1 to 11.8.

**Comment by Peyphour** [comment]
A little off topic here ^^

Anyway, I think locking the state of the GUI is the best idea

**Comment by FrancYescO** [comment]
Just reload pokémon list after a power-up/evolve? (Like was done in the GUI reported by @Turtizzle)

**Comment by Peyphour** [comment]
The REST API already do that

**Comment by FrancYescO** [comment]
So, just discussing on a non-issue ^^

Hope we will have the REST API merged soon so we can start working on the rocket theme :P

**Comment by smileytechguy** [comment]
I'd love to help! message me or something when its merged

**Comment by Sieberkev** [comment]
The build-in webserver has been removed and replaced with [external GUI](https://github.com/jabbink/PokemonGoBot/tree/gh-pages#custom-de-centralized-guis)'s.

ATM there is already one GUI (TTL55) which supports the REST API, but feel free to add yours if you want to compete ^_^
