### ISSUE TITLE
Can't get link Token from google

### ISSUE THREAD

**Issue by Jobzakung** [jabbink/PokemonGoBot#1080]
Hello 

I'm cant login because not have Token

**Comment by Sadfaffel** [comment]
You dont need token.

**Comment by patzor** [comment]
no need api token

**Comment by Jobzakung** [comment]
When loop show profile status can't login

**Comment by patzor** [comment]
make sure the bot is the only one currently logging in no one else..

**Comment by jabbink** [comment]
Hi @Jobzakung,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two weeks (until 2016-08-17 17:41) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by yashendra2797** [comment]
Ok, so here's what you need to do. Fill in the the email and the password in the respective fields, but leave `token=` blank. Don't touch it.

**Comment by Jobzakung** [comment]
OK. thank  everybody :)

**Comment by yashendra2797** [comment]
@jabbink Mark as closed please 😊
