### ISSUE TITLE
using the bot now 2-3 hours will be softban, tseted it in 3 days

### ISSUE THREAD

**Issue by zhoushifeng8** [jabbink/PokemonGoBot#1081]
Current bot setting really not working, will be ban in 3 hours of starting using bot. softban 4 times in 3 days. Is it any update or setting to avoid this?

**Comment by JonHX** [comment]
softbans last like a minute i don't see the issue?

**Comment by nhodges** [comment]
I have reduced my walk speed to 2 meters per second and it seems to help a lot. Also make sure to follow roads. Keep your unwanted Pokemon at 0 catch rate -- I have also added a bunch to my unwanted list.

@JonHX there's a new soft ban where you can still look Pokestops but you cannot catch any Pokemon.

**Comment by pvase666** [comment]
Running bot with 1m/s walking speed. Never get softban for 24 hours.

**Comment by zhoushifeng8** [comment]
@pvase666 @nhodges Thank you, i change speed to 1m/s.

**Comment by AlexBoulyga** [comment]
If you want you can usey additions: #1047 running With 2.8 and no bans

**Comment by GonnaLoseItAll** [comment]
Same problem over here! Just got 2 accounts softbanned in the last 24 hours. At the moment my walking speed is 4.0.

**Comment by jabbink** [comment]
Hi @zhoushifeng8,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two weeks (until 2016-08-17 17:41) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by gielie** [comment]
I used 2 new accounts for the last 2 hours with normal settings and both accounts have been bannend by now. Walk speed was 2.3.

Is it possible they use different detecting method now.

**Comment by AlexBoulyga** [comment]
Version 0.6? What are your settings for randomization? The New settings in Version 0.6? What is your speed etc?

**Comment by gielie** [comment]
# PTC/Google login credentials
username=******

# Choose plaintext or base64'd password
password=******
base64_password=

# Proxy server and port to be used by the bot. Only HTTP proxy are supported at the moment
proxy_server=
proxy_port=-1
# Proxy type, among SOCKS/HTTP/DIRECT. DIRECT means a direct connection i.e : no proxy
proxy_type=SOCKS
# Proxy authentication
proxy_username=
proxy_password

# Token to login directly
token=
latitude=52.0665711
longitude=4.221243100000038

# Desired probability to catch Pokemon with 1 throw
desired_catch_probability=0.4

# Desired probability to catch unwanted Pokemon (obligatory_transfer; low IV; low CP)
# Set to -1 to not attempt catching at all
desired_catch_probability_unwanted=0.0

# Set if random ball throws should be enabled
# Currently decides if the throw is nice/great/excellent/normal by using the desired_catch_probability(_unwanted), decreasing earned exp and fang rate however
# Heavily depends on the desired catch rates now, if you have too few excellent/great throws try increasing those values
random_ball_throws=true

# Set if you want to wait a little between throws (0-3 secs)
wait_between_throws=3

# Number of nearest unused pokestops to randomly select
# The next pokestop from (1/infinite)
random_next_pokestop_selection=5

# Should the bot camp around lured x pokestops (-1 = off; 1 = one needs to be in range; 2 = two..., etc)
camp_lure_pokestop=1

## Walking
# Meters per second
speed=2.3

# Random speed range around the original speed value in Meters per Second
# Example: If speed is 2.8, and the range 0.5, the speed will be between 2.3 and 3.3
random_speed_range=0.5

# Should the bot follow the streets (true) or just go directly to pokestops/waypoints
follow_streets=true

# Should the bot loot the pokestops (true/false)
loot_pokestop=true

# Should the bot catch pokemons (true/false)
catch_pokemon=true

# Should the bot auto fill incubators with eggs (true/false)
auto_fill_incubator=true

## Items drop
# Should the bot EVER drop items (true/false)
drop_items=true

# Max number of each item that the bot should keep if "drop_items" is enabled
# Use -1 in an item to never drop this specific item
# The default values add up to 350
item_revive=20
item_max_revive=10
item_potion=0
item_super_potion=30
item_hyper_potion=50
item_max_potion=50
item_poke_ball=40
item_great_ball=50
item_ultra_ball=50
item_master_ball=10
item_razz_berry=20
item_lucky_egg=-1
item_incense=-1
item_lure_module=-1

# Groups the items that are kept by type so it keeps best of same type
# Ex: if you have item_revive=20 and item_max_revive=10 and set this
#   to true, if you get 25 item_revive and 20 item_max_revive it will
#   drop 15 item_revive and keep 10 item_revive and 20 item_max_revive
# Items that have -1 are excluded from groups
# Ex: if you set item_potion=-1 it will only group the other potions and
#   ignore item_potion (never dropping item_potion)
group_items_by_type=false

## Extra Info
# Should the bot display rewards pokestop (true/false)
display_pokestop_rewards=true

# Should the bot display if it caught a pokemon from a lure (true/false)
display_if_pokemon_from_lure=true

# Should the bot display rewards when catching pokemon (true/false)
display_pokemon_catch_rewards=true

# Display keepalive coordinates
display_keepalive=true

# Should the bot display information of where it's walking to (true/false)
# This will show the name of the pokestop that it's walking to and
#   replace on the loot log the pokestop id for its name
# WARNING:  this will increase the https requests without any need. If
#           the servers are slow it's recommended to turn off this setting
display_pokestop_name=false

## Pokemon Transfer
# Should the bot auto transfer duplicate pokemon
autotransfer=true

# Minimum amount of pokemon type to keep
keep_pokemon_amount=4

# Maximum amount of pokemon type to keep (-1 to keep all)
max_pokemon_amount=-1

# Sort by IV first instead of CP
sort_by_iv=false

# Rate for bot to throw a curveball, between 0 (never) and 1 (always)
desired_curve_rate=0.5

# Never use berries
never_use_berries=false

# Allow leaving the starting area
allow_leave_start_area=false

# Max distance from starting point the bot should ever go in meters
# (-1: only limited by the initial pokestops (~3*3km); with allow_leave_start_area=true unlimited)
spawn_radius=-1

# Number of times the pokestop should be spun to attempt softban bypass (0 to disable, 40 recommended value to work)
ban_spin_count=0

# Set timer in seconds to go back to the starting pokestop (-1 disabled)
timer_walk_to_start_pokestop=-1

# Set profile update timer (Default: 60)
profile_update_timer=120

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=80

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=400

# Minimum CP % in relation to max CP of pokemon to your current trainer lvl to keep pokemon (to disable CP%:use -1)
# e.g. Trainer lvl is 33, captured EEVEE has 490 CP which results in max possible CP of 984 with 15/14/15 IV
# that however is below the threshold of 60% because its 49%
transfer_cp_min_threshold=-1

# List of pokemon you don't want to transfer regardless of CP
# The names must be divided by a ","
# If you want all pokemons to be transferred just leave it blank
ignored_pokemon=

# List of pokemon you always want to transfer regardless of CP
obligatory_transfer=

# list of pokemon you always want to evolve before transfer to maximize XP
evolve_before_transfer=CATERPIE,RATTATA,WEEDLE,PIDGEY

# The stack of evolves needed to pop lucky egg and evolve all
evolve_stack_limit=50

# Use lucky egg before transfer (1 = yes, anything else = no)
use_lucky_egg=1

# Port where the socketserver should listen, 0 = do not listen
gui_port_socket=8001

# Export player/pokemondata on Profile Update. Options are:
#   *empty*  Don't export (default)
#   CSV      Correct USA/UK CSV format ("," as delimiter and "." as decimal separator)
#   DSV      European CSV/DSV format (";" as delimiter and "," as decimal separator)
#              Use this one if your MS Excel can't handle the default CSV option
#   JSON     JSON format
export=

# Initial map size (S2 tiles) to fetch (max. 9: ~3*3km area)
initial_map_size=9

# For artificial pauses/rests
# Chance to wait randomly at a pokestop in %, recommended about 10 or less, default disabled
wait_chance=10

# Time to wait in seconds, recommended 5-30, default disabled
wait_time_min=5
wait_time_max=30

**Comment by AlexBoulyga** [comment]
Wait_between_throws should be "true" and not 3, that might be one Problem. Another setting which doesnt relate here is the camp_lure_pokestop which you habe set to 1. this makes the bot simply wait at a single pokestop that has a lure module until this runs out. I would set it to -1 vor atleast 3.
Please try this With a New ACC, if you still get banned i dont know...

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
