### ISSUE TITLE
Bot does not walk

### ISSUE THREAD

**Issue by gligi** [jabbink/PokemonGoBot#1091]
**Description:**
Not sure if this is the expected behavior but the bot walks at the start to nearby pokestop and stays there for hours (days). do i need to configure something different?

**Java version:**
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~14.04-b14)

**Comment by AlexBoulyga** [comment]
Are there any errors in the log? Does he just stop moving? If yes, have you set the camp_lure _pokestop option?

**Comment by patzor** [comment]
how long you put on this configurations

# For artificial pauses/rests
# Chance to wait randomly at a pokestop in %, recommended about 10 or less, default disabled
wait_chance=0.0

# Time to wait in seconds, recommended 5-30, default disabled
wait_time_min=0
wait_time_max=0

**Comment by nostyler** [comment]
My guess is it is related to the route provider. 

I am seeing these kind of errors:

`15 Aug 16:12:11 [default: PokestopLoop] - Error fetching route from provider: Connection timed out`

I am trying to switch (back) from yournavigation.org to project OSRM to validate this, but I am failing miserably ;)

**Comment by Sieberkev** [comment]
> Error fetching route from provider: Connection timed out

It will fall back to a straight route after some seconds

**Comment by AlexBoulyga** [comment]
There is now a "fix" which, on connection time out, sinply starts walking straight instead oft waiting forever

**Comment by gligi** [comment]
tnx

**Comment by jabbink** [comment]
Hi @gligi,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two weeks (until 2016-08-17 17:41) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by gligi** [comment]
Well with 0.6.0 works as expected :) the issue can be closed..
