### ISSUE TITLE
Dont Get it

### ISSUE THREAD

**Issue by trevorantram** [jabbink/PokemonGoBot#1092]
Please help me fix this
<img width="1280" alt="screen shot 2016-08-15 at 10 25 46 am" src="https://cloud.githubusercontent.com/assets/18074199/17667377/b4c78842-62d2-11e6-8da1-67bbe73ac575.png">

**Comment by Sieberkev** [comment]
Make sure to kill all running JAVA processes and try again.

**Comment by jabbink** [comment]
Hi @trevorantram,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two weeks (until 2016-08-17 17:41) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by parnunu** [comment]
I think this issue is port conflict maybe 8080 or 8001.
Only 8001 is configurable in config.properties or json file.
If it is 8080 you need to close other application that use that port.

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
