### ISSUE TITLE
Is value of Pokemons Encountered	from csv is correct?

### ISSUE THREAD

**Issue by soemsri** [jabbink/PokemonGoBot#1096]
**Description:**
Is value of following is correct from file export_default.csv ?

Pokemons Encountered	21
Pokemons Captured	21

**Steps to reproduce:**

see file export_default.csv

**Expected behavior:**
two value of "Pokemons Encountered"	and "Pokemons Captured	" should not equal because real catch monster hard to equal. This may be cause to ban.

**Actual behavior:**
"Pokemons Encountered"	equal "Pokemons  Captured" all times	

**Version:**
0.6.0

**Operating System:**
Winows10

**Java version:**
1.8.0_101

**Comment by AlexBoulyga** [comment]
I recently modified it, try using the actual developing branch, in my case about each 5th Pokémon flees, maybe less

**Comment by jabbink** [comment]
Hi @soemsri,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-17 18:45) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
Main account (banned): ![image](https://cloud.githubusercontent.com/assets/3216851/17671837/5103f45c-6319-11e6-972c-68d28a226810.png)

New account: ![image](https://cloud.githubusercontent.com/assets/3216851/17671803/2ac26f62-6319-11e6-9502-69b4bf24b2ec.png)

These are values that are read out from the API and do not stay equal forever since you can't catch em all ;)
