### ISSUE TITLE
For new wait function wait time

### ISSUE THREAD

**Issue by parnunu** [jabbink/PokemonGoBot#1098]
For new wait function wait time, is it logout?
I think it better to logout sometime and login again with token.

**Comment by AlexBoulyga** [comment]
I dont know What you mean, tell me exactly the Name oft the Option

**Comment by jabbink** [comment]
Hi @parnunu,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-17 19:40) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by parnunu** [comment]
For wait time function that use these parameter "wait_chance wait_time_min and wait_time_max".
When bot wait what does it do, only pause?
I suggest that it should logout and relogin with token after wait time end.
It not a human behavior that always be online.

**Comment by AlexBoulyga** [comment]
Those wait times are only small amounts to wait at pokestops, and he only stops moving. Logout and relogin is yet too difficult for me. The first priority is to escape from the bot-catching bots from niantic. Imitiating humans is only second in priority

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
