### ISSUE TITLE
Kotlin: Unresolved reference: JSONObject

### ISSUE THREAD

**Issue by marcelaraujo** [jabbink/PokemonGoBot#1099]
**Description:**
I can't build the bot with the commented router provider instead of using defaults

**Steps to reproduce:**

1. Change the route provider to use the commented provider
2. gradlew build

**Expected behavior:**
Build runs with no errors

**Actual behavior:**
Error:(71, 27) Kotlin: Unresolved reference: JSONObject

**Version:**
0.6.0

**Operating System:**
Mac OS X 10.11.6

**Java version:**
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by jabbink** [comment]
Hi @marcelaraujo,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-17 19:40) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by jabbink** [comment]
Uhm ignore that bot. No idea why it flagged this.

**Comment by nostyler** [comment]
Please be aware that OSRM has changed it's API since this code was rendered obsolete.

**Comment by nostyler** [comment]
Oh and add 'compile group: 'org.json', name: 'json', version: '20160212' to gradle.build

**Comment by marcelaraujo** [comment]
@nostyler I solved using the Jackson module but I've changed that part of source.

**Comment by marcelaraujo** [comment]
@jabbink I'll create a PR with changes which are better than use regex to extract route geometries.

**Comment by Sieberkev** [comment]
The RouteProvider functionality has been rewritten :)
