### ISSUE TITLE
[Potential Issue] Bot walks in circle multiple times, hitting the same Pokestops

### ISSUE THREAD

**Issue by MacDogg** [jabbink/PokemonGoBot#1101]
**Description:**
Trainer get stuck walking in a circle over and over, going to the same Pokestops over and over.

**Steps to reproduce:**
1. Started bot with spawn_radius=1500, random_next_pokestop_selection=1
2. Trainer goes on random path but eventually get stuck in a circular loop after a while.  This has happened in two different locations on the map when I start him at.

**Expected behavior:**
Bot should not revisit the same pokestop within X minutes so it doesn't get the **try again** message??  Not sure if this is something to be worried about but will there be a Pokemon spawn issue if you keep going to the same place?  Don't want to limit Pokemon catches because I am going over the same path over and over.

**Actual behavior:**
Although the bot has walked in the circle inside the green box over and over 7 times so far in the attached file, it has not hit the same pokestops too fast.  But can and will that happen?
I did set timer_walk_to_start_pokestop=3600 to send him back to start over.

**Version:**
0.6.0

**Operating System:**
Win10 Ultimate 64-bit

**Java version:**
java version "1.8.0_101

![walkingloop](https://cloud.githubusercontent.com/assets/20782190/17675261/a24c7404-62ee-11e6-97aa-7f08d5707de1.JPG)

**Comment by jabbink** [comment]
Hi @MacDogg,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-17 20:45) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by MacDogg** [comment]
Where I have my bot there are multiple pokestops in the area where you can hit three while standing in the same place.  I noticed the bot would hit one and then move instead of hitting all three.  Will changing that setting make it skip two of the three?
I'll restart when he returns to the start location and see what happens.  Thanks for the suggestion.

**Comment by AlexBoulyga** [comment]
Random_next.... =1 means that it always goes to the closest one, AS it usually takes the x closest one and randomly (more or less). Decides which to visit. In yout case X is 1 so i wonder how it works at all

**Comment by MacDogg** [comment]
Looks better this time.  I went to the same place and hit a few of the stops but moved on across the river.  Glad the bot water walks!!
Looks like this is resolved by a config change.  Thanks, y'all.

**Comment by jabbink** [comment]
>it has not hit the same pokestops too fast. But can and will that happen?

Should never happen
