### ISSUE TITLE
Pausing to catch Pokemon

### ISSUE THREAD

**Issue by Scar18** [jabbink/PokemonGoBot#1102]
Got this after 40 minutes.

15 Aug 14:02:50 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:02:53 [default: PokestopLoop] - Looting nearby pokestop 7fac3f2e0a5b46ff9c890d122e71d9b5.16
15 Aug 14:02:53 [default: PokestopLoop] - Looted pokestop 7fac3f2e0a5b46ff9c890d122e71d9b5.16; +50 XP: [3xITEM_POKE_BALL]
15 Aug 14:02:56 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:03:01 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:03:05 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:03:10 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:03:11 [default: WalkingLoop] - Destination reached.
15 Aug 14:03:11 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:03:12 [default: PokestopLoop] - Your character now moves with: 2.8 Meters per second
15 Aug 14:03:12 [default: WalkingLoop] - Walking to (37.808959, -122.413754) in 148.54742245576782 steps.
15 Aug 14:03:13 [default: PokestopLoop] - Looting nearby pokestop b2f9d89e774f4b5cad45b8388fa47099.12
15 Aug 14:03:14 [default: PokestopLoop] - Looted pokestop b2f9d89e774f4b5cad45b8388fa47099.12; +50 XP: [1xITEM_POTION, 2xITEM_POKE_BALL]
15 Aug 14:03:15 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:03:20 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:03:25 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:03:29 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:03:32 [default: PokestopLoop] - Looting nearby pokestop 20a4ae25ab2343b5894a768adb41fbd7.16
15 Aug 14:03:33 [default: PokestopLoop] - Looted pokestop 20a4ae25ab2343b5894a768adb41fbd7.16; +50 XP: [3xITEM_POKE_BALL]
15 Aug 14:03:35 [default: WalkingLoop] - Pausing to catch pokemon...
15 Aug 14:03:40 [default: WalkingLoop] - Pausing to catch pokemon...

**Comment by jabbink** [comment]
Hi @Scar18,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-17 21:05) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by patzor** [comment]
@Scar18 Adjust this settings on your config

## Walking
# Meters per second
speed=2.8

# For artificial pauses/rests
# Chance to wait randomly at a pokestop in %, recommended about 10 or less, default disabled
wait_chance=0.0

# Time to wait in seconds, recommended 5-30, default disabled
wait_time_min=0
wait_time_max=0

**Comment by adaur** [comment]
Yeah, same issue here.

**Comment by pet90210** [comment]
same issue here
