### ISSUE TITLE
Bot not always follow the streets

### ISSUE THREAD

**Issue by gise88** [jabbink/PokemonGoBot#1103]
**Description:**
The bot does not always follow the streets in the last version..
I have moved from https://github.com/jabbink/PokemonGoBot/commit/1a26b387d593f1d6472c6bf01d7cc57fd19280bc to the latest commit (https://github.com/jabbink/PokemonGoBot/commit/4af28bca49fec5ccddf7047225791690882c855c) and something goes wrong with follow_streets function.

**Steps to reproduce:**
Don't know.. :cry: 

**Expected behavior:**
Having selected "follow_streets", the bot should follow the street (every time or almost)

**Actual behavior:**
![followstreet](https://cloud.githubusercontent.com/assets/6855163/17676295/2c435a6c-632e-11e6-9371-98cab67991a4.png)

**Stacktrace (If it's a crash):**
No crash

**Version:**
https://github.com/jabbink/PokemonGoBot/commit/4af28bca49fec5ccddf7047225791690882c855c

**Operating System:**
Debian 8

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by jabbink** [comment]
Hi @gise88,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-17 21:40) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
The external RouteProvider is suffering from of a LOT of traffic, the bot falls back to a straight line to avoid standing still forever...

**Comment by gise88** [comment]
Oh, ok! This is a bad news... :confused: Is impossible to use Google Maps as RouteProvider?

**Comment by mineme45** [comment]
#1105

**Comment by CptJackieSparrow** [comment]
In my case, it never follows streets :smile:

**Comment by Sieberkev** [comment]
#1113 implemented a new RouteProvider, can you pull the most recent version and try again pls? :)

**Comment by AlexBoulyga** [comment]
For me the New one works alot better :)
Thanks @Sieberkev

**Comment by crayse1** [comment]
18 Aug 16:22:14 [default: WalkingLoop] - Destination reached.
18 Aug 16:22:15 [default: PokestopLoop] - Error fetching route from provider: Server returned HTTP response code: 503 for URL: http://yournavigation.org/api/dev/route.php?flat=29.626831442051934&flon=-95.59647105015098&tlat=29.627306000000004&tlon=-95.59608&v=foot&fast=1

My bot will not follow the streets.

**Comment by Sieberkev** [comment]
You will have to wait for a new release (or get the development version running) to get the fix for that :)
