### ISSUE TITLE
[Enhancement] Setting to force using follow street

### ISSUE THREAD

**Issue by mineme45** [jabbink/PokemonGoBot#1105]
If the Route API is down, the bot do not follow street.
Add a setting to force the bot to retry the API call. (with a Thread.sleep to avoid spam the API).
While the API do not answer, the bot do not move.

**Comment by jabbink** [comment]
Hi @mineme45,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-17 22:00) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by mineme45** [comment]
I will make a pull request soon

**Comment by gise88** [comment]
Another options instead of `force follow streets` (= waits for Route Provider) is to not create a straight line to the destination.. So, just create a sort of zigzag path (?) near the straight line.. I do not believe that Niantic can checks all the roads we have traveled to see if they are correct.. No? 
If the RouteProvider is down the bot will remains firm, even for hours.. :cry:

Or maybe better, trying to decode GoogleMaps polylines?
Getting direction from [Google Maps](https://maps.googleapis.com/maps/api/directions/json?origin=40.722764,-73.996917&destination=40.722504,-73.991617&avoid=highways&mode=walking&key=<MY_API_KEY>) returns something like this http://pastebin.com/6C01Vr0y

If you open that: https://developers.google.com/maps/documentation/utilities/polylineutility and enter the `overview_polyline.points` (`itpwFxosbMkCy@YSMM|@sCdA_Dv@yCx@mCJ[yA_@XgBx@cEQG`) inside the "Encoded Polyline:" field and press "Decode Polilyne" -> Ok, it will list all locations (coordinates) of the points! 

Good point: GoogleMaps never goes down
Bad point: Users have to create your own key to use GoogleMaps Api

**Comment by mineme45** [comment]
We can try to use this :
https://github.com/googlemaps/google-maps-services-java

**Comment by gise88** [comment]
I don't know kotlin (so I can't do a pr) but in java this seems to be easy:
http://pastebin.com/rqdGGC46

**Comment by AlexBoulyga** [comment]
As far as i know the bot never travels a straight line but always a little zigzag (AS a human loooking at his phone would)
The own API key would limit multiple bots
AS niantic is part of google i would not recommend using their services because oft easier recognition (they could search for their own GPS pattern)

**Comment by mineme45** [comment]
There is an another API using OpenStreetMap :
mapzen.com
It's free, we need an api key but it's look like unlimited.

**Comment by jabbink** [comment]
@gise88 every decent IDE has Java to Kotlin auto conversion.

**Comment by muschter** [comment]
@gise88 Perhaps using IntelliJ IDEA would help you out.

**Comment by gise88** [comment]
> @gise88 every decent IDE has Java to Kotlin auto conversion.

Probably I am not using a very decent ide! :joy: Are you all using IntelliJ?

**Comment by muschter** [comment]
I personally use IntelliJ.

**Comment by AlexBoulyga** [comment]
I use intellij too. However kotlin is really similar to Java, i have never used it before, not even seen it

**Comment by mineme45** [comment]
There is a java to kotlin converter but no kotlin to java converter  : (

**Comment by mineme45** [comment]
I working on.a mapzen alternative as Route Provider

**Comment by mineme45** [comment]
#1167
