### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by Alist3r** [jabbink/PokemonGoBot#1111]
**Description:**
When i'm attempting to login i got this error 
![bot error](https://cloud.githubusercontent.com/assets/6814806/17691642/126764d6-6396-11e6-8849-bf3d97a00a8f.png)

**Steps to reproduce:**

1. Open the CMD and use the command to run the bot
2. Wait the login until i got the error

**Expected behavior:** The bot should run normally

**Actual behavior**: Actully after the message "Login into the game server" i got a java error

**Stacktrace (If it's a crash):** just check the screenshot 

**Version:**
Version 0.6.0 

**Operating System:**
Windows 7

**Java version:**
1.8

**Comment by jabbink** [comment]
Hi @Alist3r,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-18 09:50) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Alist3r** [comment]
I've added the missing information

**Comment by AlexBoulyga** [comment]
Can you retry running it? And tell me if the same error happens

**Comment by staurakis** [comment]
Currently there are issues with their servers. I have received the known message that their servers have problems using a PTC login.

**Comment by Alist3r** [comment]
Before open the ticket i tryed 4 times and always got the error. Now the bot works

**Comment by staurakis** [comment]
Yes my point exactly....there are many server issues currently... They are not all bans...

**Comment by Sieberkev** [comment]
> Exception: Read timed out in request handler

Problems with the niantic servers, will close this issue since it is not a bot problem o/
