### ISSUE TITLE
found some bug on version0.6.0

### ISSUE THREAD

**Issue by e-thee** [jabbink/PokemonGoBot#1137]
1).  Rest not work.
 I see the message "Trainer grew tired, needs to rest a little (for 19 seconds)" in log file, but bot still walking not rest like message said

> 17 Aug 16:06:41 [bot: WalkingLoop] - Destination reached.
> 17 Aug 16:06:42 [bot: PokestopLoop] - Trainer grew tired, needs to rest a little (for 19 seconds)
> 17 Aug 16:06:44 [bot: BotLoop] - Getting map of (xxx.xxx, yyy.yyy) 
> 17 Aug 16:06:49 [bot: BotLoop] - Getting map of (xxx.xxx, yyy.yyy) 
> 17 Aug 16:06:54 [bot: BotLoop] - Getting map of (xxx.xxx, yyy.yyy) 
> 17 Aug 16:06:59 [bot: BotLoop] - Getting map of (xxx.xxx, yyy.yyy) 
> 17 Aug 16:07:01 [bot: PokestopLoop] - Your character now moves with: 0.9055115717791794 Meters per second
> 17 Aug 16:07:01 [bot: WalkingLoop] - Walking to (xxx.xxx, yyy.yyy) in 749.8117359085342 steps.

2). "followStreets" option not work
 ["followStreets" : true,] in JSON file not work (see result in WebUI) bot still walk to pokestops directly

3). Error Message "Error fetching route from provider: Server returned HTTP response code: 503 for URL: http://..."
I don't know why the bot shows this message.

Version: 0.6.0
Operating System: Windows 10
Java version: java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) Client VM (build 25.102-b14, mixed mode, sharing)

**Comment by AlexBoulyga** [comment]
Read 3 and you will understand 2. i will look at 1 and why it doesnt work

**Comment by jabbink** [comment]
Hi @e-thee,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-19 12:20) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by e-thee** [comment]
@AlexBoulyga how can I fix problem 3?

**Comment by Sieberkev** [comment]
> 17 Aug 16:06:42 [bot: PokestopLoop] - Trainer grew tired, needs to rest a little (for 19 seconds)
17 Aug 16:07:01 [bot: PokestopLoop] - Your character now moves with: 0.9055115717791794 Meters per second

That's exactly 19 seconds :-°

3 is fixed in development branch (and next release)

**Comment by e-thee** [comment]
Oh, I think "Getting map of..." is walking bot, sorry.

and one more thing, it's be better if rest time can be configure and random

waiting a new launch
thanks everyone.

**Comment by Sieberkev** [comment]
> and one more thing, it's be better if rest time can be configure and random

wait_chance=12.5
wait_time_min=7
wait_time_max=25

**Comment by AlexBoulyga** [comment]
the wait time IS random between wait_time_min and wait_time_max :)
I use for 
wait_chance = 10
min=10
max=40
but that are just my settings

**Comment by e-thee** [comment]
T_T it's my faults again

I don't know "wait" is the rest time
