### ISSUE TITLE
Cannot understand API login process

### ISSUE THREAD

**Issue by MaxFrax** [jabbink/PokemonGoBot#1139]
i'm not able to understand how to login to rest APIs.
The required parameter {name} is my player's nick name?
Should I post as body this raw string? `rest_api_password`
If I try this combination I get 400 error as shown below
![immagine](https://cloud.githubusercontent.com/assets/3145452/17735888/13eb9706-6485-11e6-90fc-850b53d04702.png)

(i'm using postman)

**Comment by jabbink** [comment]
Hi @MaxFrax,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-19 14:20) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by JoeyyT** [comment]
If using config.properties use: localhost:8001/api/bot/default/auth
Then u should get an auth key :)

**Comment by Sieberkev** [comment]
8001 is the socket port per bot (to fetch the most recent data), you need to use port 8080.
The {name} is the name of your bot (= `default` by default).
The `rest_api_password` is a random value you have to configure in your config.properties file (see config.properties.template if you don't have it already).

Firstly you need to do the auth with in the raw body the random value of `rest_api_password`, then you will get a random token back. Use that token in the `X-PGB-ACCESS-TOKEN` header in all other calls.

**Comment by MaxFrax** [comment]
@Sieberkev thank you! It works!
I think updating API.md with this informations would be a good idea, do you agree?

**Comment by MaxFrax** [comment]
<img width="949" alt="schermata 2016-08-17 alle 16 34 25" src="https://cloud.githubusercontent.com/assets/3145452/17740348/98f5bcca-6498-11e6-9573-5beb06d879d7.png">

Well I'm having another issue, I get 200 when I try any get request but I don't receive any content

**Comment by Sieberkev** [comment]
Does `/api/bot/default/pokemons` work? It's possible some of the endpoints need more testing :)

**Comment by MaxFrax** [comment]
No, it doesn't. I also tried other get requests and it was the same

**Comment by Jobzakung** [comment]
@MaxFrax can tech me how to get token. i dont unerstand

**Comment by Sieberkev** [comment]
This is a working [proof of concept with javascript](https://gist.github.com/Sieberkev/0f96f190615cebf15a07ca2a8a2a61ca). Save it to your desktop (or wherever), open it in your browser, make sure the bot is running, press "Auth" (this will fetch a token), press "Fetch Pokemons" to get a JSON string with all your pokes.

**Comment by Mixone-FinallyHere** [comment]
I cant get any of this to work

**Comment by Peyphour** [comment]
Anyone still doesn't undertstand ?

**Comment by MaxFrax** [comment]
Have you read the API.md file?

@Sieberkev I haven't tried the javascript yet, I'm pretty busy these days.

**Comment by Peyphour** [comment]
@MaxFrax works for you ?

**Comment by MaxFrax** [comment]
@Peyphour I got the token, but all the GET requests return 200 without content

**Comment by Peyphour** [comment]
200 without content means that the token is wrong

**Comment by Peyphour** [comment]
Make sure that you keep the latest token, each call to /auth generate a new one

**Comment by MaxFrax** [comment]
Well, this is bad API design for me. If the token is wrong should be returned 401 or 403

**Comment by Peyphour** [comment]
Yeah that's true, the api still needs some work

**Comment by Sieberkev** [comment]
I've added HTTP status codes in PR
