### ISSUE TITLE
Weird error when starting jar file

### ISSUE THREAD

**Issue by beaubeire** [jabbink/PokemonGoBot#1141]
What does this mean and what is the solution? See attachment

![knipsel](https://cloud.githubusercontent.com/assets/17483284/17737371/1739ea9a-648d-11e6-94e7-a822098ed5fe.JPG)

**Comment by jabbink** [comment]
Hi @beaubeire,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-19 15:15) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
> Address already in use

Kill all running java processes, wait a min, restart again.

Exit the bot with `ctrl+c` instead of just closing the window (it keeps running in the background then).

**Comment by muschter** [comment]
You can kill all running java processes with the command: "taskkill /f /im java.exe"
