### ISSUE TITLE
Build Failed (tried FAQ, installed JDK, no luck)

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#1151]
ink.abb.pogo.scraper.TestSettings > testDefaultSettings FAILED
    java.io.FileNotFoundException at TestSettings.kt:25

ink.abb.pogo.scraper.TestSettings > testTemplateKeys FAILED
    java.io.FileNotFoundException at TestSettings.kt:73

2 tests completed, 2 failed
:test FAILED

**Comment by jabbink** [comment]
Hi @CptJackieSparrow,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-19 20:30) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
> java.io.FileNotFoundException at TestSettings.kt:25
> java.io.FileNotFoundException at TestSettings.kt:73

Is the file "config.properties.template" in the root directory of the project? If you want to use it, make a copy to config.properties, don't rename it :)

**Comment by CptJackieSparrow** [comment]
let me check it maybe it's been erased after gradlew clean build

**Comment by Sieberkev** [comment]
Are you in the root project of the bot when you build it? What's the exact command you use?

(the error is it can't find the file, so something is wrong with the location)

**Comment by CptJackieSparrow** [comment]
here's what i've did:
1)There's a file in C:\Users\"user"\PokemonGoBot
2)I have JRE (can run v0.6.0 bot) and JDK (u8 101) installed.
3)I'm typing:
cd C:\Users\"user"\PokemonGoBot
gradlew build
4) Then i got this error: http://pastebin.com/xCTKHhqk

**Comment by Sieberkev** [comment]
Can you post a screenshot of the `dir` commando in that directory? This will show a list of all files in the directory

**Comment by CptJackieSparrow** [comment]
http://pastebin.com/TqM2Ni77 here's dir command on directory

**Comment by Sieberkev** [comment]
That looks correct tho...

Computers, right ¯\_(ツ)_/¯

**Comment by CptJackieSparrow** [comment]
yeah what ever nothing i can do :smile:

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
