### ISSUE TITLE
Evolve and transfer scripting

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#1156]
I'm wondering if the bot will automaticly save 1 pokemon for each stack of candies that match the evolve?

If i have like 100 pidgey candies, will the bot automaticly save like 9 pidgeys to be able to evolve them all later depending on what evolve stack limit I've set?

**Comment by jabbink** [comment]
Hi @Leodenact,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-20 02:05) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by FrancYescO** [comment]
yes.

**Comment by AlexBoulyga** [comment]
Hey will save only 8 (8x12=96) i believe, even with 102 candys, although theoretically 102 are enough for 10 pidgeys

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
