### ISSUE TITLE
Full ban?

### ISSUE THREAD

**Issue by Killertom63** [jabbink/PokemonGoBot#1158]
Ever since everyone started getting temp bans, my account got banned too. However, I can only find that they are temp bans? Can anyone offer any info to if there is a perma ban because I cannot still access my account? 

Thanks

**Comment by jabbink** [comment]
Hi @Killertom63,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-20 08:00) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by AlexBoulyga** [comment]
There is a permaban since one week. I have seen 2 kinds of them myself: One were the server simply refuses to get data, and it hangs on the loading screen ( in the real app), and one where it says "server error"

**Comment by Killertom63** [comment]
Ok, that's good to know. Just wanting to make sure. Thanks @AlexBoulyga
