### ISSUE TITLE
Catch_Flee Ban

### ISSUE THREAD

**Issue by Scar18** [jabbink/PokemonGoBot#1169]
Got the Catch_Flee ban even after staying under 1001 Pokemons and 2000 Pokestops in 23 hours. There's gotta be a way that they detect this.

**Comment by jabbink** [comment]
Hi @Scar18,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-21 00:40) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by KyleBoyer** [comment]
It should be under 1000 pokemon, so if you hit 1k that explains it

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
