### ISSUE TITLE
how to remove ban account?

### ISSUE THREAD

**Issue by thestarclubz** [jabbink/PokemonGoBot#1171]
my account has a can't login. because my account it is ban! T_T

how to it ?

**Comment by jabbink** [comment]
Hi @thestarclubz,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-21 06:15) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
Create a new profile and replace the login credentials in the configuration files.

If you mean the official client: reinstall it and you can enter a new login.
