### ISSUE TITLE
Some Pokemon's icon broken

### ISSUE THREAD

**Issue by vinh1508** [jabbink/PokemonGoBot#1182]
http://pokeapi.co/media/sprites/pokemon/21.png
![20160820-1471655297](https://cloud.githubusercontent.com/assets/16659562/17827803/87075e08-66ad-11e6-9009-b68e52f74d7b.png)

**Comment by jabbink** [comment]
Hi @vinh1508,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-22 03:10) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by vinh1508** [comment]
Sorry, This's first time I comment here :)

**Comment by FrancYescO** [comment]
there and already open PR https://github.com/eruecco87/PokemonGoBot-RocketTheme/pull/24

not here the right place to report
