### ISSUE TITLE
Bot doesn't follow the streets? Just goes directly in straight lines to PokeStops?

### ISSUE THREAD

**Issue by Muwai** [jabbink/PokemonGoBot#1195]
I got the setting enabled to follow streets, but it doesn't work.

Cheers.

**Comment by jabbink** [comment]
Hi @Muwai,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-23 10:15) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by mineme45** [comment]
Error message?
You probably use the release (jar).
It's fixed on the develop branch.

**Comment by Muwai** [comment]
@mineme45 I use the .jar as i'm on a Mac. Can you explain to me how to use the develop branch?

**Comment by mineme45** [comment]
https://github.com/jabbink/PokemonGoBot/blob/develop/USAGE.md#from-source
