### ISSUE TITLE
How to run from source on Mac?

### ISSUE THREAD

**Issue by Muwai** [jabbink/PokemonGoBot#1209]
I followed the instructions to run from source, but the command gradlew build doesn't work. It just says command not found.
This command works though: git clone https://github.com/jabbink/PokemonGoBot.git && cd PokemonGoBot

Cheers.

**Comment by FrancYescO** [comment]
./gradlew build ?

**Comment by jabbink** [comment]
Hi @Muwai,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-24 09:55) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Muwai** [comment]
Still doesn't work

**Comment by CptJackieSparrow** [comment]
1. open terminal
2. execute `cd (drag and drop file location)`
3. execute `java -jar PokemonGoBot-0.6.0.jar`

**Comment by CptJackieSparrow** [comment]
oh from source, ./gradlew build, then ./gradlew run

**Comment by pzibit** [comment]
There might be a problem with your java runtime environment. You have to change the path before each start, so that the bot works with java 8.

Use this command: 
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"

Then do:
1. cd /users/(yourname)/(path to file)
2. java -jar PokemonGoBot-0.6.0.jar

**Comment by Sieberkev** [comment]
This should do the trick. I'll close the issue for now, if any new problems arise, you can start a new issue :)
