### ISSUE TITLE
Bot not following streets with Google API Key?

### ISSUE THREAD

**Issue by Muwai** [jabbink/PokemonGoBot#1221]
I got the Key, is there anything i got to do after it to make the bot follow the streets? If there is can someone please walk me through step by step. Cheers.

My config is set to true btw.

**Comment by alone23** [comment]
Set GOOGLE

**Comment by jabbink** [comment]
Hi @Muwai,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-25 01:05) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Resistant-X** [comment]
For me the bot wanted to follow no roads. I always gotten an error message from yournavigation.org. I have looked at the source code and made a small change.

In FIle
src\main\kotlin\ink\abb\pogo\scraper\util\directions\RouteRequest.kt
In line 42 change
    return "$routeProvider?flat=$olat&flon=$olng&tlat=$dlat&tlon=$dlng&v=foot&fast=1"
to
    return "$routeProvider?flat=$olat&flon=$olng&tlat=$dlat&tlon=$dlng&v=bicycle&fast=1"

Now I have no more error messages from yournavigation.org and my bot follows again the streets.
![unbenannt](https://cloud.githubusercontent.com/assets/1244755/18002741/ef684404-6b89-11e6-8dc6-131af4dca640.PNG)

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
