### ISSUE TITLE
Can't show the GUI

### ISSUE THREAD

**Issue by EiTeR94** [jabbink/PokemonGoBot#1223]
Description:

I got the default setting, but i can't see the GUI, i go to http://ui.pogobot.club/, use the original UI, and nothing is update, the bot still running fine.

Steps to reproduce:

   1 Run bot
   2 go to http://ui.pogobot.club/
   3 Click Original UI

Expected behavior:
Get the GUI working

Actual behavior:
nothing is show, just the default windows, blank, no log etc.

Version:
7ac65b2 

Operating System:
Win10

Browser:
Mozilla Firefox 48.0

Java version:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by jabbink** [comment]
Hi @EiTeR94,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-25 10:20) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by EiTeR94** [comment]
hope it's fine like this?

**Comment by FrancYescO** [comment]
^ you have no t added the last sentence.

browser?

**Comment by EiTeR94** [comment]
added :)

**Comment by FrancYescO** [comment]
what i mean is that you got the incomplete issue tag cause you forgot to add the last row of the template

the only tip that i can give you is to try with chrome other browsers seems don't like these gui

**Comment by EiTeR94** [comment]
oh, you mean the sentence must really be on at the end? lol, added then.
Will try with Chrome

**Comment by Sieberkev** [comment]
Do you get an error in your console that the bot can not "[address already in use](https://github.com/jabbink/PokemonGoBot/blob/develop/FAQ.md#i-get-address-already-in-use)"?

**Comment by EiTeR94** [comment]
It's work on chrome, but not on FF, so i will use chrome for the bot. thank.
