### ISSUE TITLE
Opition to stop bot.

### ISSUE THREAD

**Issue by ck196** [jabbink/PokemonGoBot#1224]
- Now PokemonGo have new ban type like 2000 pokemonstop lot, 1000 pokemons caught,
Should we add some options in config file to stop bot.

- Example max_pokemon_caught=xxx, max_pokemonstop_lot=xxx?

Do anyone have other good suggestions ?

**Comment by jabbink** [comment]
Hi @ck196,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-25 11:10) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
There is already a PR in the pipeline for this (#1095)
