### ISSUE TITLE
Transferring pokemons IV>90% despite settings

### ISSUE THREAD

**Issue by Boomstamtak** [jabbink/PokemonGoBot#1225]
I hatched a 91% IV Ponyta, it transferred it immediately because my maximum pokemons to keep was 4 (i already had 4 ponytas). The CP of the Ponytas i already had was larger than the one i hatched but the IV was the highest of all Ponytas, still it transferred. My IV to keep is set to 90%. Is this an error in the code or an error in the properties?

**Comment by jabbink** [comment]
Hi @Boomstamtak,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-25 12:30) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by AlexBoulyga** [comment]
It is an error in the logic. You have 4 ponitas. You said keep max 4 ponitas. Guess what the bot does - he keeps 4 ponitas. The first 4. I agree it would be better if the bot transferred the worst ponita. But then again, how should he decide which is the worst. CP? Iv? Attacks?

**Comment by joligario** [comment]
Sort by IV if that is more important than CP.
