### ISSUE TITLE
Should the bot camp around lured x pokestops

### ISSUE THREAD

**Issue by proteste-dcm** [jabbink/PokemonGoBot#1226]
**Description:**
If I understood correctly, this variable should make the bot stay around the X nearest pokestops. And this is not happening.

f.e: I set the variable as 3 and the bot starts in a coordinate and after 30 minutes it is kilometers away.

**Steps to reproduce:**

1. configure all the file config.properties
2. configure the variable "camp_lure_pokestop" equals 3 f.e
3. wait some time and you'll see that the bot is too far from the beginning

**Expected behavior:**
I expected the bot stay hanging around the 3 poke stops closer to where he started

**Actual behavior:**
I set the variable as 3 and the bot starts in a coordinate and after 30 minutes it is kilometers away

**Version:**
develop. until august 23

**Operating System:**
ubuntu 14

**Java version:**
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by jabbink** [comment]
Hi @proteste-dcm,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-25 22:35) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by proteste-dcm** [comment]
It seems that I answered all points of the default template.
I do not know what is missing. Sorry

**Comment by mineme45** [comment]
"Lured" pokestop

**Comment by Cypherke** [comment]
It camps pokestop with lures on, it doesn't camp regular pokestops. So if you set camp_lure_pokestop = 3, then 3 pokestops with lures have to be in range of your player to stop walking and camp. If less then 3 pokestops are in range and have a lure in place, the bot will just continue walking. If you dont want to walk, put walk speed to 0.
