### ISSUE TITLE
Evolving goes too fast, Error running loop ProfileLoop! as result after 10-15 evolves

### ISSUE THREAD

**Issue by gielie** [jabbink/PokemonGoBot#1230]
Running latest dev version.

When stack to evolve is enabled and there are enough pokemons to evolve it will start evolving.
But after 10-15 evolves i get an "Error running loop ProfileLoop!"
So i think the evolving process goes too fast, there should be a pauze between evolves.

tried this several times with same result.

**Comment by FrancYescO** [comment]
https://github.com/jabbink/PokemonGoBot/pull/1095

**Comment by jabbink** [comment]
Hi @gielie,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-26 13:30) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
Known issue, will be fixed with a combination of the new API and #1095
