### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by neXusBRA** [jabbink/PokemonGoBot#1261]
Description: BUILD FAILED

Steps to reproduce:

1. gredle build
2. gradlew run

Expected behavior: Complete the bot installation
Actual behavior: Failed to build

Stacktrace:
Pastebin: http://pastebin.com/wg7785bc

Version: 0.6.0

Operating System: Ubuntu x64

Java version:-
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Screenshot's -
Command "gradle build": http://prntscr.com/cce7ar
Command "./gradlew clean build" : http://prntscr.com/cce7pw

I do not know , I'm using the download command in the tutorial from source)

Hello , I'm already trying to install multiple pokemongo bot in my vps ( ubuntu ) and to this day I could not install any alone, please help me . I searched on the internet tutorials on how to install gradle and java installed both and efetuei steps bot tutorial, but when I will give the command " build gradle " I'm getting error BUILD FAILED . I will leave a pastbin and a screenshot , hope to get aid. 

NOTE : I tried two commands: "gradlew build" and" "./gradlew clean build" both did not work.
NOTE²: Sorry for the English , I'm using google translator
NOTE³: do not know version, I'm using the download command in the tutorial from source

**Comment by jabbink** [comment]
Hi @neXusBRA,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-09-02 09:30) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
For the first error: Do not use `gradle`, but the bundled `gradlew` command (that's a wrapper with a working version, the default preinstalled-on-your-system gradle can be too old).

The second error (which is with the correct `gradlew` command) is because it can't find any valid configuration template files in the root directory (config.properties.template and json-template.json).

**Comment by neXusBRA** [comment]
I put the file missing config.properties.template , and used the command ./gradlew build ant ./gradlew clean build , this time gave me a hope to complete , but in the end he 's failed again. Could you help me again ?

New error: http://pastebin.com/z5dnd8HT

**Comment by Sieberkev** [comment]
What's the output in `/root/PokemonGoBot/build/reports/tests/index.html`?

**Comment by neXusBRA** [comment]
http://prntscr.com/ccl9k7

**Comment by Sieberkev** [comment]
Mmyeezzzzz, but what is IN the file, if you open the index.html file in your browser, what are the errors in the report?

**Comment by neXusBRA** [comment]
Sorry ! http://prntscr.com/cclqqn

**Comment by Sieberkev** [comment]
Uhu, so you have 2 failed tests and some blue links under that, what does those say?

**Comment by neXusBRA** [comment]
Sorry friend, did not understand what you mean, I'm using google translator, what should I do to solve this error ?

**Comment by Sieberkev** [comment]
If you click those, what does it say?

![b2112e935abc4f8686f38bf8a9ca8cb3](https://cloud.githubusercontent.com/assets/3216851/18144567/8ef4b1ce-6fc7-11e6-9499-769c9556e59b.png)

**Comment by neXusBRA** [comment]
I get error , not for nothing by clicking the link http://prntscr.com/ccnixu
But if I go in this file and open as Notepad I have some information : http://pastebin.com/yTwMqAYq

**Comment by neXusBRA** [comment]
bro?

**Comment by Sieberkev** [comment]
I would recommend you wait until the new release is ready so you can use the JAR file, which does not require building the source. Building the bot from source is not even that hard, but it looks like you have no idea what you are doing.

The two files in your root directory `[config.properties.template](https://github.com/jabbink/PokemonGoBot/blob/develop/config.properties.template)`and `json-[template.json](https://github.com/jabbink/PokemonGoBot/blob/develop/json-template.json)` are not the default files, this is why the build fails. Download them from the links above, replace your current template files and DO NOT EDIT THEM, leave them as they are.

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
