### ISSUE TITLE
Got 0 Pokestop

### ISSUE THREAD

**Issue by ejisen001** [jabbink/PokemonGoBot#1272]
Please help me for fix this issue.
This issue start from yesterday until now.
I can logged to pokemon go on my smartphone normal.

**Comment by jabbink** [comment]
Hi @ejisen001,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-09-04 14:15) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
[FAQ](https://github.com/jabbink/PokemonGoBot/blob/develop/FAQ.md#the-bot-doesnt-findloot-pokestops)
