### ISSUE TITLE
403 Forbidden when getting pokemon images

### ISSUE THREAD

**Issue by AmazingGamerBoy** [jabbink/PokemonGoBot#1276]
Hi, when I use the rocketThemeGui, I always get this error:
![image](https://cloud.githubusercontent.com/assets/15712937/18264153/edf13d44-7451-11e6-8236-f6c8d209bc22.png)

I also get this error before and after I install an extension for origin headers. Though when I have the extension installed, it gives me an error that says that I can't use a wildcard like '*' as an origin header.
![image](https://cloud.githubusercontent.com/assets/15712937/18264094/82f8587e-7451-11e6-86f6-75c2db879b8b.png)

**Comment by jabbink** [comment]
Hi @AmazingGamerBoy,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-09-08 08:50) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by AmazingGamerBoy** [comment]
@jabbink just fixed it

**Comment by AmazingGamerBoy** [comment]
@jabbink damnit
