### ISSUE TITLE
No pokèstops

### ISSUE THREAD

**Issue by crazyhoorse961** [jabbink/PokemonGoBot#1283]
**Description:**
Everytime i start the hack (tried to reinstall too) it gives me an error. Or like, he cannot find pokèstops.

**Steps to reproduce:**
1.Start the bot
2.Wait 

**Expected behavior:**
Start the bot correctly, catch pokèmon and get pokèstops.

**Actual behavior:**
When the bots start it gives an error.

**Stacktrace:**
http://pastebin.com/dDnwwbjG
P.s:In some cases it says like ''Cannot fetch https://www.google.com/maps/@42.499805,-17.524591,3z''
EDIT: config:http://pastebin.com/MqZLJK03

**Version:**
0.6.0

**Operating System:**
Windows 10 Home Edition 64bit

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Thank you

**Comment by jabbink** [comment]
Hi @crazyhoorse961,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-09-11 20:30) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
