### ISSUE TITLE
New security measures

### ISSUE THREAD

**Issue by ajhalls** [jabbink/PokemonGoBot#1300]
FYI, the app now may ask for a captcha on logging in. I got a warning on one of my accounts that 3rd  party software had been detected. The bot software no longer runs. Thank you for the good times and the help, I must admit that I play the game more in real life because I had the bot, than if I didn't.

**Comment by jabbink** [comment]
Hi @ajhalls,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-10-08 01:45) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by staurakis** [comment]
Hello, 
the problem with the current situation is not the captcha question. I am sure the developers of the bot will find a workaround. However, what is frightening is the message that they know and they have flagged our accounts that used bots and they can delete these accounts with the press of a button as they did previously. In other words, few weeks now, since the previous time, they knew which people were using bots and they let them play like that most probably in order to show good statistics after the massive drop in their user base. Which of course is a smart move.

**Comment by MacDogg** [comment]
What a bummer, oh well.  Doesn't work on bluestacks, either.

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
