### ISSUE TITLE
is this an information?

### ISSUE THREAD

**Issue by FriendlyBear013** [jabbink/PokemonGoBot#1303]
well since the update of the pokemon go
Usually I use the bot directly well I noticed that I'm getting 0 pokestops and like 2 pokemons caught

then I use the app itself they have now like a captcha thing when you first log in to the app every now and then

the captcha must've been blocking the bot itself or causing some limitations to it

not blocking but more like putting a limit

that's all I have for now

ill post if I find others stuff

**Comment by jabbink** [comment]
Hi @FriendlyBear013,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-10-12 12:40) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
