### ISSUE TITLE
The Usage MD from source is not up to date

### ISSUE THREAD

**Issue by smileytechguy** [jabbink/PokemonGoBot#1311]
On the file USAGE.md the instructions for building are out of date

It should use bot-settings, right?

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by jabbink** [comment]
Hi @smileytechguy,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-11-15 17:25) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by jabbink** [comment]
Uhm, both work. The properties file will be converted to json automatically.
