### ISSUE TITLE
Pokemon releasing is based on CP, rather then IV/both

### ISSUE THREAD

**Issue by ToMeRhh** [jabbink/PokemonGoBot#181]
maybe we should implement a custom comparator for the pokemonGroup sort...  

I'm referring to this line:
`val sorted = it.value.sortedByDescending { ****** }`

(By 'based' I mean that the very first decision is based on CP, later, the IV is also checkd...)

#172

**Comment by megatixos** [comment]
Agree, someone should make this first to check the IV (its more important imo) then CP

**Comment by Forty-Tw0** [comment]
I brought this up in #171 and proposed the change in #208

**Comment by Forty-Tw0** [comment]
This is now implimented. Example settings to keep pokemon with the highest IVs:

# Sort by IV first instead of CP
sort_by_iv=true

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=-1

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=-1

**Comment by dvasko** [comment]
is there any setup for keeping highest IVs AND CP > xxx.
because now if i have one krabby with 100% IV, 10CP and other with 99% IV and 600CP bot would transfer second krabby which is meh...
