### ISSUE TITLE
Latest Release (0.4) Tried to Incubate eggs ever few lines

### ISSUE THREAD

**Issue by cglatot** [jabbink/PokemonGoBot#229]
**Description:**
In the console I get the error "Failed to put egg in incubator: error: ERROR_POKEMON_ALREADY_INCUBATING every 2-4 lines. Seems like an awful lot of requests. Is this intended? If so, can we get an option to reduce how often it tries to incubate eggs, or at least remove it from the console output? Really clogs it up.

**Steps to reproduce:**
1. Ensure there are eggs in your inventory
2. Make sure all incubators are in use currently (but have free eggs)

**Expected behavior:**
Not sure?

**Actual behavior:**
See Description

**Stacktrace (If it's a crash):**
Example console output (Coordinates removed):

> 24 Jul 21:19:19: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
> 24 Jul 21:19:23: Getting map of ()
> 24 Jul 21:19:23: Destination reached.
> 24 Jul 21:19:23: Walking to () in 172.92307402028914 steps.
> 24 Jul 21:19:23: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
> 24 Jul 21:19:28: Getting map of ()
> 24 Jul 21:19:28: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
> 24 Jul 21:19:33: Getting map of ()
> 24 Jul 21:19:33: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
> 24 Jul 21:19:38: Getting map of ()
> 24 Jul 21:19:38: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
> 24 Jul 21:19:43: Getting map of ()
> 24 Jul 21:19:44: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
> 24 Jul 21:19:48: Getting map of ()
> 24 Jul 21:19:48: Looting nearby pokestop 
> 24 Jul 21:19:48: Looted pokestop; +50 XP: [1xITEM_GREAT_BALL, 2xITEM_POKE_BALL]
> 24 Jul 21:19:49: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
> 24 Jul 21:19:53: Getting map of ()
> 24 Jul 21:19:53: Dropped 2x ITEM_POKE_BALL
> 24 Jul 21:19:53: Dropped 1x ITEM_GREAT_BALL
> 24 Jul 21:19:54: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
> 24 Jul 21:19:57: Destination reached.
> 24 Jul 21:19:58: Getting map of ()
> 24 Jul 21:19:58: Profile update: 443295 XP on LVL 23; 8295/125000 (6.64%) to LVL 24
> 24 Jul 21:19:58: XP gain: 600 XP; Pokemon caught/transferred: 1/33; Items caught/dropped: 25/65; Pokebank 279/1000; Stardust 119356
> 24 Jul 21:19:58: Walking to () in 178.55014212724868 steps.
> 24 Jul 21:19:58: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
> 24 Jul 21:20:03: Getting map of ()
> 24 Jul 21:20:03: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
> 24 Jul 21:20:08: Getting map of ()

**Version:**
0.4 Release

**Comment by lz0** [comment]
Can confirm.

**Comment by TechnoDaft** [comment]
I was just about to post same issue with more info i'll just add here

**Description:**
tries to incubate but fails {seems it's trying to use an incubator already in use}

**Steps to reproduce:**
Not entirely sure maybe have all but 1 incubator with same "uses" left and 1 with 1 less use it may be confusing the bot

**Expected behavior:**
use an empty incubator

**Actual behavior:**
24 Jul 16:17:42: Getting map of (40.764909164475135, -73.97247439196565)
24 Jul 16:17:44: Walking to pokestop "The Metropolitan Club"
24 Jul 16:17:44: Walking to (40.764916, -73.972457) in 0.8596070877888496 steps.
24 Jul 16:17:44: Destination reached.
24 Jul 16:17:44: Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING
![untitled](https://cloud.githubusercontent.com/assets/20615768/17086434/fc931278-51bf-11e6-8b44-10dc77c8ec6c.png)
![screenshot_2016-07-24-16-57-44](https://cloud.githubusercontent.com/assets/20615768/17086440/09ba1d2a-51c0-11e6-9063-91b1f366147a.png)

**Version:**
Pokemon Go Bot v0.4.0 {pre-built java pre-release}

**Comment by jabbink** [comment]
Same as #228 

bug in Java API... smh

**Comment by jabbink** [comment]
Bugfix in https://github.com/Grover-c13/PokeGOAPI-Java/pull/190
