### ISSUE TITLE
Error when logging second time

### ISSUE THREAD

**Issue by victorespada** [jabbink/PokemonGoBot#395]
**Description:**
I have an error when try to logging and the config "token" has a value.

**Steps to reproduce:**

1. Logging first time
2. Logging second time and crash

**Expected behavior:**
Should be logging

**Actual behavior:**
Crash!

**Stacktrace (If it's a crash):**
26 jul 12:49:34: Display Keepalive Coordinates setting ("display_keepalive") not specified, defaulting to "true". 
Logging in to game server...
Exception in thread "main" java.lang.IllegalStateException: if (token.contains("poke…eshToken(token)
        } must not be null
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:90)

**Version:**
[0.4.3] with jar on debian 8.3

**Comment by omar972** [comment]
Open config.properties and clear the token= field.

**Comment by victorespada** [comment]
Yes, but then I need to go to google.com/devices and put new code... Is it necessary if i have a token?

**Comment by omar972** [comment]
On the latest release, the bot puts in the temporary token in the config file instead of the static token, so the token in the config is useless. When you put the new code from google.com/devices, the bot outputs both these tokens in the logs but puts in the wrong one in the config. To fix this, either manually replace the one in the config with the short one-line one that appears after "Logged in as EMAIL" or compile from the develop build which automatically puts in the correct one.

**Comment by victorespada** [comment]
Thanks! I did't read the text 

Logged in as xxxx@gmail.com with token xxxxxxxxxxxxxxxxx
Setting this token in your config

Thanks!

**Comment by Sieberkev** [comment]
This is fixed in the next release :) (it is now IF you run it from the develop tree source)

**Comment by jabbink** [comment]
Should be fixed with 0.4.3
