### ISSUE TITLE
I don't see the point of this commit

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#482]
https://github.com/jabbink/PokemonGoBot/commit/ca37e4ed77b3646a4f4f3ce3ade6ebc83f06258c

This commit adds the number of eggs the user has to the number of Pokemon they have. This seems like it would cause confusion for no reason. Most of the time, the user will have 9 eggs anyway, but if it's really needed there should be a separate counter for number of eggs.

**Comment by jabbink** [comment]
1. Most of the time an avid bot user will have 0 or 1 eggs.
2. People complained that the bot said the inventory was not full, even though it was full. This happens because the official client counts eggs in your pokebag limit. Eg you have 241 items, and you think: sweet, I can store 9 more pokemon, only to see that your pokebag is full, because you had 9 eggs.

**Comment by omar972** [comment]
I had no idea it actually counts them, thanks for answering.
