### ISSUE TITLE
Possible To Transfer based on Moveset/IV

### ISSUE THREAD

**Issue by cwliias** [jabbink/PokemonGoBot#508]
Is it possible to selectively transfer based on the Move set before IV? Or Just the Move set?

**Comment by xslkz** [comment]
not atm

**Comment by Emuuung** [comment]
Move set is not an implemented variable in the bot yet, but I think it should be since it is another key variable to pick the most potentially powerful pokemons.

**Comment by Forty-Tw0** [comment]
# Sort by IV first instead of CP
sort_by_iv=true

# minimum amount of pokemon type to keep
keep_pokemon_amount=2

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=-1

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=-1

**Comment by Emuuung** [comment]
@Forty-Tw0 ? erm, yeah, those are **OTHER** already implemented variables to work around.

**Comment by langerhans** [comment]
Closing in favor of #566 since it has some valuable info on the topic.
