### ISSUE TITLE
Some questions about the config in the latest update

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#513]
Can some expain this in a noob friendly way

1. "port where the webserver (gui) should listen" 
2. "Never use berries" What happens if I don't use berries? Why wouldn't I wanna use them?
3. "random_next_pokestop_selection=5"  Will this mean that it's randomly walking to one of the five it currently sees? So it will walk a long way from starting place since it will discover 5 new when it's arrived on the new destination?

Cheers

**Comment by jabbink** [comment]
>"port where the webserver (gui) should listen"

Port where the UI will be, default http://localhost:**8000**

>"Never use berries" What happens if I don't use berries? Why wouldn't I wanna use them?

Some people complained that they didn't want to use berries, so you can disable the usage of them now.

>"random_next_pokestop_selection=5" Will this mean that it's randomly walking to one of the five it currently sees? So it will walk a long way from starting place since it will discover 5 new when it's arrived on the new destination?

Instead of going to the closest from the current point, it will randomly (weighted) select one of the `x` (=5) closest (from the current position).
