### ISSUE TITLE
[possible bug] using level up items

### ISSUE THREAD

**Issue by accident12123** [jabbink/PokemonGoBot#573]
i'm 50/50 on if this is happening but I did a couple hour test and then went into the app to see what eggs looked like and found I had some incubators that never got used.   As soon as the bot was restarted it immediately placed eggs into them but while running it wasn't noticing it had any.

It's probably a bug where a few minutes after leveling up you need to pull the item list or maybe just do it periodically (every 10-25% or maybe every x XP is a better trigger since there can be a delay in getting more stuff after a level up.

**Comment by MASSV** [comment]
I think the issue is the bot/api does not properly receive level up bonus items. They dont show up on my account til I login with blustacks or a phone using the real app. and when i do it pushes all of them out at once and can push over inventory limits. Same thing happens with achievements/badges, they dont register as getting them until logged in with real app.

**Comment by citruz** [comment]
Probably the same thing that happened in #494. I also noticed this problem but wasn't 100% sure either.

**Comment by Sieberkev** [comment]
Fixed/implemented in #1075
