### ISSUE TITLE
How to use automatic login?

### ISSUE THREAD

**Issue by EpicAwesomeWolf** [jabbink/PokemonGoBot#60]
Can't seem to get it working without using google.com/device

**Comment by VoxelBirthday** [comment]
I was wondering this as well... not to mention, I have no clue what token I'm supposed to get and where. There's no details.

**Comment by EpicAwesomeWolf** [comment]
Yeah. I tried with the google.com/device token, a OAuth 2.0 client key, nothing seemed to work. It also says "saving in config" but it doesn't save anything.

**Comment by RaeneDev** [comment]
Only thing I can think of would unless I'm doing something incorrectly be possibly a feature from the settings for club accounts or something.

**Comment by EpicAwesomeWolf** [comment]
I hope they add an automatic Google login, I don't wanna reset D:

**Comment by RaeneDev** [comment]
Same not to mention after around 30 or so minutes it begins tossing errors like it was disconnected. Auto login would be much more simple than this auto hotkey script I made lol.

**Comment by EpicAwesomeWolf** [comment]
Yeah. Seems like I'm not catching any Pokemon either...

**Comment by PancakeZik** [comment]
After a first login, copy the token from the command prompt and paste on your config file, under token.
Works for me

**Comment by jabbink** [comment]
>It also says "saving in config" but it doesn't save anything.

It should never say that. It gives you a token and says "Set this token in your config to log in directly"

This has only be tested with PTC accounts (which got you kicked out after ~20 minutes before and now since this version my bot is running for 3h straight already without an error).

>I have no clue what token I'm supposed to get and where. There's no details.

Sorry, leave it empty and the next time you start the bot it will tell you the token you have to put in there in the console

>I hope they add an automatic Google login, I don't wanna reset D:

Coming. Soon :tm: 

>Same not to mention after around 30 or so minutes it begins tossing errors like it was disconnected.

That's what the `token=` is for. Only verified to work with PTC though.

**Comment by RaeneDev** [comment]
Ah c: Thank you @jabbink I was wondering if it affected google accounts at all. I use google so maybe that's why it didn't say anything. Really look forward in the automatic google login!

**Comment by PancakeZik** [comment]
I was talking about google, and it works for me. Just copy the token.
