### ISSUE TITLE
No login available when a "." is included (gmail)

### ISSUE THREAD

**Issue by superkilerpokemon** [jabbink/PokemonGoBot#665]
**Description:**
No login available with an email adress like this: xyz.qwe@gmail.com

**Version:**
0.5.0 alpha 3

**Operating System:**
win 10 64bit
**Java version:**
Build 1.8.0_101-b13

**Comment by cglatot** [comment]
Remove the dots. Funny story, gmail doesn't actually recognise dots, so you can have as many or as few:

https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html

**Comment by superkilerpokemon** [comment]
doesn't work, sadly.

**Comment by Boraida** [comment]
Weird Ive a "." aswell in my gmail, but I can login.

**Comment by superkilerpokemon** [comment]
@Boraida are you using Boraida?

**Comment by derekbaalmann** [comment]
Using Alpha 3 and 4 I have this same issue. All PTCs I use work, about 120 throwaways (didn't test all of these...) and 3 good ones I created the first week the game came out. All Google accounts tested (tried 3, again setup around when the game came out) and only 2 of the 3 work. The one that doesn't work is of course the one with the "." in it. 
I do understand and KNOW about google ignoring periods (all 3 of the good PTC accounts were made by moving the period around in my address to basically get more emails/accounts from one gmail (before PTC account maker)) but it doesn't work. Removing the period doesn't work. Also I can't login to google with my normal xx.xxxx@gmail.com by trying xxxxxx@gmail.com or xxx.xxx@gmail.com. Seems you can send emails to xxx.xxx@gmail.com and they go to xx.xxxx@gmail.com but I can't use xxx.xxx@gmail.com to sign in.

**Comment by Cypherke** [comment]
2 factor authentication on or off?

**Comment by derekbaalmann** [comment]
Good point, the account with the "." in it DOES have 2 factor turned on, where the other two I was testing with do not.
Might be the problem. I tried again with 0.4.3 and instead of the usual "Have user go to google.com/device and input XXXXXX" it gave "Have user go to [null] and input [null].
So basically that one account with 2-factor auth and a "." in it can't login on any version. As a side note PokeMobBot logs in fine, full game logs in fine, and it used to log in fine when 0.4.3 was the latest release. I'm going to say that sometime after 0.4.3 the google auth system was changed as the older versions of the bots now returns [null] instead of a code or the google.com/device.

**Comment by Cypherke** [comment]
have you tried generating an application password for that 2fa account? https://accounts.google.com/ServiceLogin?service=accountsettings&continue=https://security.google.com/settings/security/apppasswords&hl=en&sarp=1&passwdsession=true&osid=1&authuser=0

**Comment by derekbaalmann** [comment]
That works, thanks. Just weird how it went from working to having to go this route instead.

**Comment by jabbink** [comment]
Yeah, 2FA isn't implemented in the fake GApps auth. Should add to readme
